# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: "123" 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: mysite_development
  pool: 5
  username: postgres
  password: "123"  # Đảm bảo mật khẩu này khớp với mật khẩu trong ci.yml
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: mysite_test
  pool: 5
  username: postgres
  password: "123"  # Phải khớp với POSTGRES_PASSWORD
  host: localhost

production:
  primary: &primary_production
    <<: *default
    database: mysite_production
    username: mysite
    password: <%= ENV["MYSITE_DATABASE_PASSWORD"] %>
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: mysite_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mysite_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mysite_production_cable
    migrations_paths: db/cable_migrate
