name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for all bin files
        run: chmod +x bin/*  # Cấp quyền thực thi cho tất cả các tệp trong thư mục bin

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version  # Sử dụng phiên bản Ruby từ file .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install  # Cài đặt phụ thuộc thông qua Bundler

      - name: Run Brakeman
        run: bin/brakeman --no-pager  # Quét bảo mật Rails

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for importmap
        run: chmod +x bin/importmap

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit  # Quét bảo mật cho JavaScript

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for rubocop
        run: chmod +x bin/rubocop

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github  # Kiểm tra mã nguồn theo quy tắc RuboCop

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install  # Cài đặt tất cả phụ thuộc

      - name: Run database setup
        run: bin/rails db:create db:migrate  # Tạo và di chuyển cơ sở dữ liệu

      - name: Run tests
        run: bin/rails test  # Chạy các bài kiểm tra

      - name: Set execute permissions for bin/rails
        run: chmod +x bin/rails  # Cấp quyền thực thi cho tệp rails

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: bin/rails db:test:prepare test test:system  # Chạy kiểm tra hệ thống

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
